export interface VehiculeInterface {
    vehiculeId:string;
    Type_vehicule:string;
    matricule:string;
    Nombre_place:string;
    modele:string;
    marque:string;
    annee:string;
    numero_chassis:string;
    couleur:string;
    nombre_porte:string;
    type_Carburent:string;
    transmission:string;
    puissance:string;
    kilometrage:string;
    nombre_Chevaux:string;
    documents:string;
    valide:string;
    contracts:string;
    constat:string;
    amende:string;
    userModification:string;
    dateModification:string;
}